version: '3'

services:
  webserver:
    image: nginx:mainline-alpine 
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx-conf:/etc/nginx
      - ./nginx-conf/mime.types:/var/conf/mime.types
  drone:
    image: drone/drone:2
    container_name: drone
    restart: unless-stopped
    ports:
      - "443:443"
    volume:
      - /var/lib/drone:/data
    env_file:
      - variables.env
  